-- MySQL Script generated by MySQL Workbench
-- Sun Sep 27 23:49:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema raizes_nordeste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema raizes_nordeste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `raizes_nordeste` DEFAULT CHARACTER SET utf8 ;
USE `raizes_nordeste` ;

-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_regiao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_regiao` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_regiao` (
  `id_regiao` INT NOT NULL AUTO_INCREMENT,
  `nm_regiao` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id_regiao`),
  UNIQUE INDEX `nm_regiao_UNIQUE` (`nm_regiao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_unidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_unidade` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_unidade` (
  `id_unidade` INT NOT NULL AUTO_INCREMENT,
  `id_regiao` INT NOT NULL,
  `nm_unidade` VARCHAR(45) NOT NULL,
  `ds_logradouro` VARCHAR(150) NOT NULL,
  `nr_endereco` VARCHAR(10) NOT NULL,
  `ds_complemento` VARCHAR(100) NULL,
  `nm_cidade` VARCHAR(100) NOT NULL,
  `sg_uf` CHAR(2) NOT NULL,
  `nr_cep` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_unidade`),
  INDEX `fk_tb_unidade_tb_regiao_idx` (`id_regiao` ASC) VISIBLE,
  CONSTRAINT `fk_tb_unidade_tb_regiao`
    FOREIGN KEY (`id_regiao`)
    REFERENCES `raizes_nordeste`.`tb_regiao` (`id_regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_unidade` INT NULL,
  `nm_usuario` VARCHAR(100) NOT NULL,
  `ds_email` VARCHAR(65) NOT NULL,
  `ds_senha` VARCHAR(255) NOT NULL,
  `nr_cpf` CHAR(11) NULL,
  `cd_perfil` ENUM('ADMIN', 'GERENTE', 'CLIENTE', 'COZINHA', 'ATENDENTE') NOT NULL,
  `flg_ativo` TINYINT NOT NULL DEFAULT 0,
  `qt_pontos` INT(7) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tb_usuario_tb_unidade1_idx` (`id_unidade` ASC) VISIBLE,
  UNIQUE INDEX `ds_email_UNIQUE` (`ds_email` ASC) VISIBLE,
  UNIQUE INDEX `nr_cpf_UNIQUE` (`nr_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_tb_unidade1`
    FOREIGN KEY (`id_unidade`)
    REFERENCES `raizes_nordeste`.`tb_unidade` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_produto` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nm_produto` VARCHAR(100) NOT NULL,
  `ds_produto` VARCHAR(255) NULL,
  `flg_ativo` TINYINT NOT NULL DEFAULT 0,
  `ds_imagem` VARCHAR(255) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_receita` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_receita` (
  `id_receita` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_receita_base` INT NULL,
  `id_unidade` INT NULL,
  `ds_receita` TEXT NOT NULL,
  `dt_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_atualizacao` DATETIME NULL,
  PRIMARY KEY (`id_receita`),
  INDEX `fk_tb_receita_tb_produto1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_tb_receita_tb_unidade1_idx` (`id_unidade` ASC) VISIBLE,
  INDEX `fk_tb_receita_tb_receita1_idx` (`id_receita_base` ASC) VISIBLE,
  CONSTRAINT `fk_tb_receita_tb_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `raizes_nordeste`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_receita_tb_unidade1`
    FOREIGN KEY (`id_unidade`)
    REFERENCES `raizes_nordeste`.`tb_unidade` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_receita_tb_receita1`
    FOREIGN KEY (`id_receita_base`)
    REFERENCES `raizes_nordeste`.`tb_receita` (`id_receita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_pedido` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_unidade` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `cd_status` ENUM('AGU_PAG', 'PAGO', 'EM_PREPARO', 'PRONTO', 'ENTREGUE', 'CANCELADO') NOT NULL DEFAULT 'AGU_PAG',
  `vl_total` DECIMAL(10,2) UNSIGNED NOT NULL,
  `dt_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_atualizacao` DATETIME NULL,
  `cd_canal` ENUM('APP', 'TOTEM', 'BALCAO', 'PICKUP', 'WEB') NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_tb_pedido_tb_unidade1_idx` (`id_unidade` ASC) VISIBLE,
  INDEX `fk_tb_pedido_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pedido_tb_unidade1`
    FOREIGN KEY (`id_unidade`)
    REFERENCES `raizes_nordeste`.`tb_unidade` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `raizes_nordeste`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_item_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_item_pedido` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_item_pedido` (
  `id_item_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `qt_produto` INT(4) UNSIGNED NOT NULL,
  `vl_unitario` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_item_pedido`),
  INDEX `fk_tb_item_pedido_tb_pedido1_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_tb_item_pedido_tb_produto1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_item_pedido_tb_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `raizes_nordeste`.`tb_pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_item_pedido_tb_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `raizes_nordeste`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_pagamento` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `vl_pagamento` DECIMAL(10,2) UNSIGNED NOT NULL,
  `cd_status` ENUM('PENDENTE', 'APROVADO', 'NEGADO') NOT NULL DEFAULT 'PENDENTE',
  `cd_transacao` VARCHAR(100) NULL,
  `dt_pagamento` DATETIME NULL,
  `dt_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_atualizacao` DATETIME NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX `fk_tb_pagamento_tb_pedido1_idx` (`id_pedido` ASC) VISIBLE,
  UNIQUE INDEX `id_pedido_UNIQUE` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pagamento_tb_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `raizes_nordeste`.`tb_pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_consentimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_consentimento` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_consentimento` (
  `id_consentimento` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `flg_consentimento` TINYINT NOT NULL DEFAULT 0,
  `dt_consentimento` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_atualizacao` DATETIME NULL,
  PRIMARY KEY (`id_consentimento`),
  INDEX `fk_tb_consentimento_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_consentimento_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `raizes_nordeste`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_auditoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_auditoria` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_auditoria` (
  `id_auditoria` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `ds_acao` VARCHAR(255) NOT NULL,
  `dt_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_auditoria`),
  INDEX `fk_tb_auditoria_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_auditoria_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `raizes_nordeste`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_unidade_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_unidade_produto` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_unidade_produto` (
  `tb_unidade_id_unidade` INT NOT NULL,
  `tb_produto_id_produto` INT NOT NULL,
  `qt_produto` INT UNSIGNED NOT NULL DEFAULT 0,
  `vl_produto` DECIMAL(10,2) UNSIGNED NOT NULL,
  `flg_disponivel` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`tb_unidade_id_unidade`, `tb_produto_id_produto`),
  INDEX `fk_tb_unidade_Produto_tb_unidade1_idx` (`tb_unidade_id_unidade` ASC) VISIBLE,
  INDEX `fk_tb_unidade_Produto_tb_produto1_idx` (`tb_produto_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_unidade_Produto_tb_unidade1`
    FOREIGN KEY (`tb_unidade_id_unidade`)
    REFERENCES `raizes_nordeste`.`tb_unidade` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_unidade_Produto_tb_produto1`
    FOREIGN KEY (`tb_produto_id_produto`)
    REFERENCES `raizes_nordeste`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_alteracao_receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_alteracao_receita` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_alteracao_receita` (
  `id_alteracao_receita` INT NOT NULL AUTO_INCREMENT,
  `id_receita` INT NOT NULL,
  `ds_receita` TEXT NOT NULL,
  `cd_status` ENUM('RASCUNHO', 'PENDENTE', 'APROVADA', 'REJEITADA') NOT NULL DEFAULT 'RASCUNHO',
  `dt_solicitacao` DATETIME NULL,
  `dt_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_atualizacao` DATETIME NULL,
  PRIMARY KEY (`id_alteracao_receita`),
  INDEX `fk_tb_historico_receita_tb_receita1_idx` (`id_receita` ASC) VISIBLE,
  CONSTRAINT `fk_tb_historico_receita_tb_receita1`
    FOREIGN KEY (`id_receita`)
    REFERENCES `raizes_nordeste`.`tb_receita` (`id_receita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raizes_nordeste`.`tb_resgate_pontos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raizes_nordeste`.`tb_resgate_pontos` ;

CREATE TABLE IF NOT EXISTS `raizes_nordeste`.`tb_resgate_pontos` (
  `id_resgate_pontos` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `qt_pontos` INT(7) UNSIGNED NOT NULL,
  `dt_resgate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_resgate_pontos`),
  INDEX `fk_tb_resgate_pontos_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_resgate_pontos_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `raizes_nordeste`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
